blank_issues_enabled: false
contact_links:
  - name: ioBroker-Forum / ioBroker forum
    url: https://forum.iobroker.net/
    about: Allgemeine ioBroker-Fragen und Hilfe bei der Einrichtung / General ioBroker questions and setup help
